# Generated by Django 6.0.6 on 2026-06-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajecontacto',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Mensaje de contacto', 'verbose_name_plural': 'Mensajes de contacto'},
        ),
    ]
