# Generated by Django 6.0.6 on 2026-06-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidente',
            options={'ordering': ['-fecha_ocurrencia'], 'verbose_name': 'Entrada del blog', 'verbose_name_plural': 'Entradas del blog'},
        ),
    ]
